// @generated by protoc-gen-es v2.10.1 with parameter "target=js"
// @generated from file whatsapp_service.proto (package whatsapp_service, syntax proto3)
/* eslint-disable */

import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_whatsapp } from "./whatsapp_pb.js";

/**
 * Describes the file whatsapp_service.proto.
 */
export const file_whatsapp_service = /*@__PURE__*/
  fileDesc("ChZ3aGF0c2FwcF9zZXJ2aWNlLnByb3RvEhB3aGF0c2FwcF9zZXJ2aWNlMnAKD1doYXRzYXBwU2VydmljZRJdChNQdXNoV2hhdHNhcHBNZXNzYWdlEiwud2hhdHNhcHBfc2VydmljZS5QdXNoV2hhdHNhcHBNZXNzYWdlUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAQhtaGWdlbnByb3RvL3doYXRzYXBwX3NlcnZpY2ViBnByb3RvMw", [file_google_protobuf_empty, file_whatsapp]);

/**
 * @generated from service whatsapp_service.WhatsappService
 */
export const WhatsappService = /*@__PURE__*/
  serviceDesc(file_whatsapp_service, 0);

